# Numpy Basics

NumPy provides an N-dimensional array type, the ndarray, which describes a collection of “items” of the *same* type.  
The items can be indexed using for example N integers.  
All ndarrays are homogeneous: every item takes up the same size block of memory, and all blocks are interpreted in exactly the same way.  
An item extracted from an array, e.g., by indexing, is represented by a Python object whose type is one of the array scalar types built in NumPy.

<p align="center">
<img src="https://numpy.org/doc/stable/_images/threefundamental.png">
</p>

## NumPy Array Attributes

In [104]:
import numpy as np
np.random.seed(0)

In [105]:
def array_info(array: np.ndarray) -> None:
    print(f"ndim: {array.ndim}")
    print(f"shape: {array.shape}")
    print(f"size: {array.size}")
    print(f"dtype: {array.dtype}")
    print(f"values:\n{array}\n")

## Array Indexing and Slicing

Array indexing refers to any use of the square brackets ([]) to index array values. There are many options to indexing, which give numpy indexing great power.

Most of the following examples show the use of indexing when referencing data in an array. The examples work just as well when assigning to an array.

Note that slices of arrays do not copy the internal array data but only produce new views of the original data.

![](../media/np_matrix_indexing.png)

In [106]:
x = np.array([[1, 2], [3, 4], [5, 6]])

array_info(x)

ndim: 2
shape: (3, 2)
size: 6
dtype: int32
values:
[[1 2]
 [3 4]
 [5 6]]



In [107]:
print(x[:3])

[[1 2]
 [3 4]
 [5 6]]


In [108]:
print(x[1:])

[[3 4]
 [5 6]]


In [109]:
print(x[1:2])

[[3 4]]


In [110]:
print(x[::-1])

[[5 6]
 [3 4]
 [1 2]]


In [111]:
print(x[0, :])

[1 2]


In [112]:
print(x[0])

[1 2]


In [113]:
print(x[:, 0])

[1 3 5]


In [114]:
mean = [0, 0]
cov = [[1, 2],
       [2, 5]]

x = np.random.multivariate_normal(mean=mean, cov=cov, size=10)

print(x)
print(x.shape)

[[-1.78290539 -3.87118733]
 [-1.76178869 -1.82780883]
 [-1.35141055 -4.32039163]
 [-0.81984535 -2.14310962]
 [-0.06176746  0.29530878]
 [-0.68960528 -0.09076013]
 [-0.74967019 -1.67816385]
 [-0.53776779 -0.93711981]
 [-1.30183841 -3.36497764]
 [ 0.03761145 -0.8336645 ]]
(10, 2)


In [115]:
rand_idxs = np.random.randint(low=0, high=x.shape[0], size=3)

print(rand_idxs)

[9 9 0]


In [116]:
print(x.shape)
x_subsample = x[rand_idxs, :]
print(x_subsample.shape)
print(x_subsample)

(10, 2)
(3, 2)
[[ 0.03761145 -0.8336645 ]
 [ 0.03761145 -0.8336645 ]
 [-1.78290539 -3.87118733]]


In [117]:
x_subsample = x[rand_idxs]

print(x_subsample)

[[ 0.03761145 -0.8336645 ]
 [ 0.03761145 -0.8336645 ]
 [-1.78290539 -3.87118733]]


## Subarrays are views

In [118]:
print(x)

[[-1.78290539 -3.87118733]
 [-1.76178869 -1.82780883]
 [-1.35141055 -4.32039163]
 [-0.81984535 -2.14310962]
 [-0.06176746  0.29530878]
 [-0.68960528 -0.09076013]
 [-0.74967019 -1.67816385]
 [-0.53776779 -0.93711981]
 [-1.30183841 -3.36497764]
 [ 0.03761145 -0.8336645 ]]


In [119]:
x_sub_array = x[:2, :2]

array_info(x_sub_array)

ndim: 2
shape: (2, 2)
size: 4
dtype: float64
values:
[[-1.78290539 -3.87118733]
 [-1.76178869 -1.82780883]]



In [120]:
x_sub_array[0, 0] = -1

array_info(x_sub_array)

ndim: 2
shape: (2, 2)
size: 4
dtype: float64
values:
[[-1.         -3.87118733]
 [-1.76178869 -1.82780883]]



In [121]:
array_info(x)

ndim: 2
shape: (10, 2)
size: 20
dtype: float64
values:
[[-1.         -3.87118733]
 [-1.76178869 -1.82780883]
 [-1.35141055 -4.32039163]
 [-0.81984535 -2.14310962]
 [-0.06176746  0.29530878]
 [-0.68960528 -0.09076013]
 [-0.74967019 -1.67816385]
 [-0.53776779 -0.93711981]
 [-1.30183841 -3.36497764]
 [ 0.03761145 -0.8336645 ]]



## Creating copies of arrays

In [122]:
x_copy = x[:2, :2].copy()

array_info(x_copy)

ndim: 2
shape: (2, 2)
size: 4
dtype: float64
values:
[[-1.         -3.87118733]
 [-1.76178869 -1.82780883]]



In [123]:
x_copy[0, 0] = 42

array_info(x_copy)

ndim: 2
shape: (2, 2)
size: 4
dtype: float64
values:
[[42.         -3.87118733]
 [-1.76178869 -1.82780883]]



In [124]:
array_info(x)

ndim: 2
shape: (10, 2)
size: 20
dtype: float64
values:
[[-1.         -3.87118733]
 [-1.76178869 -1.82780883]
 [-1.35141055 -4.32039163]
 [-0.81984535 -2.14310962]
 [-0.06176746  0.29530878]
 [-0.68960528 -0.09076013]
 [-0.74967019 -1.67816385]
 [-0.53776779 -0.93711981]
 [-1.30183841 -3.36497764]
 [ 0.03761145 -0.8336645 ]]



## Reshaping of Arrays

In [125]:
a = np.arange(start=1, stop=10)

array_info(a)

ndim: 1
shape: (9,)
size: 9
dtype: int32
values:
[1 2 3 4 5 6 7 8 9]



In [126]:
grid = np.reshape(a, newshape=(3, 3))

array_info(grid)

ndim: 2
shape: (3, 3)
size: 9
dtype: int32
values:
[[1 2 3]
 [4 5 6]
 [7 8 9]]



In [127]:
x = np.array([1, 2, 3])

array_info(x)

ndim: 1
shape: (3,)
size: 3
dtype: int32
values:
[1 2 3]



In [128]:
x = np.reshape(x, newshape=(1, 3))

array_info(x)

ndim: 2
shape: (1, 3)
size: 3
dtype: int32
values:
[[1 2 3]]



In [129]:
array_info(x)

x = x[np.newaxis, :]

array_info(x)

ndim: 2
shape: (1, 3)
size: 3
dtype: int32
values:
[[1 2 3]]

ndim: 3
shape: (1, 1, 3)
size: 3
dtype: int32
values:
[[[1 2 3]]]



In [130]:
array_info(x)

x = x.reshape((3, 1))

array_info(x)

ndim: 3
shape: (1, 1, 3)
size: 3
dtype: int32
values:
[[[1 2 3]]]

ndim: 2
shape: (3, 1)
size: 3
dtype: int32
values:
[[1]
 [2]
 [3]]



In [131]:
array_info(x)

x = x.ravel()

array_info(x)

ndim: 2
shape: (3, 1)
size: 3
dtype: int32
values:
[[1]
 [2]
 [3]]

ndim: 1
shape: (3,)
size: 3
dtype: int32
values:
[1 2 3]



In [132]:
x = x.reshape((3, 1))
array_info(x)

x = x.flatten()

array_info(x)

ndim: 2
shape: (3, 1)
size: 3
dtype: int32
values:
[[1]
 [2]
 [3]]

ndim: 1
shape: (3,)
size: 3
dtype: int32
values:
[1 2 3]



- `flatten()` always returns a copy.
- `ravel()` returns a view of the original array whenever possible. This isn't visible in the printed output, but if you modify the array returned by ravel, it may modify the entries in the original array. If you modify the entries in an array returned from flatten this will never happen. ravel will often be faster since no memory is copied, but you have to be more careful about modifying the array it returns.

### “Automatic” Reshaping

In [133]:
a = np.arange(30)

array_info(a)

ndim: 1
shape: (30,)
size: 30
dtype: int32
values:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]



In [134]:
b = a.reshape((2, -1, 3))

array_info(b)

ndim: 3
shape: (2, 5, 3)
size: 30
dtype: int32
values:
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]



## Changing the Dtype

| Numpy type | C type   | Description |
|-|-|-|
| numpy.int8 | int8_t | Byte (-128 to 127) |
| numpy.int16 | int16_t |   Integer (-32768 to 32767) |
| numpy.int32 | int32_t |   Integer (-2147483648 to 2147483647) |
| numpy.int64 | int64_t |   Integer (-9223372036854775808 to 9223372036854775807) |
| numpy.uint8 | uint8_t |   Unsigned integer (0 to 255) |
| numpy.uint16 | uint16_t |   Unsigned integer (0 to 65535) |
| numpy.uint32 | uint32_t |   Unsigned integer (0 to 4294967295) |
| numpy.uint64 | uint64_t |   Unsigned integer (0 to 18446744073709551615) |
| numpy.intp | intptr_t |   Integer used for indexing, typically the same as ssize_t |
| numpy.uintp | uintptr_t |   Integer large enough to hold a pointer |
| numpy.float32 | float |  |
| numpy.float64 | double |   Note that this matches the precision of the builtin python float. |
| numpy.complex64 | float complex |   Complex number, represented by two 32-bit floats. |
| numpy.complex128 | double complex |   Note that this matches the precision of the builtin python complex. |

In [135]:
x = np.float32([-1.0, 2.0, 3.0])

array_info(x)

ndim: 1
shape: (3,)
size: 3
dtype: float32
values:
[-1.  2.  3.]



In [136]:
x = np.array([-1.0, 2.0, 3.0], dtype=np.float32)

In [137]:
y = x.astype(np.int8)

array_info(y)

ndim: 1
shape: (3,)
size: 3
dtype: int8
values:
[-1  2  3]



In [138]:
z = np.uint16(x)

array_info(z)

ndim: 1
shape: (3,)
size: 3
dtype: uint16
values:
[65535     2     3]



## Concatenation of arrays

In [139]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

result = np.concatenate([x, y])

array_info(result)

ndim: 1
shape: (6,)
size: 6
dtype: int32
values:
[1 2 3 3 2 1]



In [140]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

array_info(grid)

ndim: 2
shape: (2, 3)
size: 6
dtype: int32
values:
[[1 2 3]
 [4 5 6]]



In [141]:
result = np.concatenate([grid, grid]) # axis=0 is default

array_info(result)

ndim: 2
shape: (4, 3)
size: 12
dtype: int32
values:
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]



In [142]:
result = np.concatenate([grid, grid], axis=0) # axis=0 is default

array_info(result)

ndim: 2
shape: (4, 3)
size: 12
dtype: int32
values:
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]



In [143]:
result = np.concatenate([grid, grid], axis=1)

array_info(result)

ndim: 2
shape: (2, 6)
size: 12
dtype: int32
values:
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]



In [144]:
x = np.array([1, 2, 3])
grid = np.array([[4, 5, 6],
                 [7, 8, 9]])

result = np.vstack([x, grid])

array_info(result)

ndim: 2
shape: (3, 3)
size: 9
dtype: int32
values:
[[1 2 3]
 [4 5 6]
 [7 8 9]]



In [145]:
y = np.array([[-1], [-1]])

result = np.hstack([grid, y])

array_info(result)

ndim: 2
shape: (2, 4)
size: 8
dtype: int32
values:
[[ 4  5  6 -1]
 [ 7  8  9 -1]]

