# Numpy ufuncs

A <mark>universal function</mark> is a function that operates on ndarrays in an <mark>element-by-element fashion (element-wise)</mark>.  
A ufunc is a “vectorized” wrapper for a function that takes a fixed number of specific inputs and produces a fixed number of specific outputs.

In [1]:
from typing import Iterable

import numpy as np
np.random.seed(0)

## Native Python Loops

In [2]:
def reciprocal(values: Iterable[float]) -> Iterable[float]:
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

In [3]:
small_array = np.random.randint(low=1, high=10, size=5)
print(reciprocal(small_array))

[0.16666667 1.         0.25       0.25       0.125     ]


| Multiple of a second | Unit | Symbol | Definition | Comparative examples & common units |
|-|-|-|-|-| 
| 10−9 | 1 nanosecond | ns | One billionth of one second | 1 ns: Time to execute one machine cycle by a 1 GHz microprocessor 1 ns: Light travels 30 cm |
| 10−6 | 1 microsecond | µs | One millionth of one second | 1 µs: Time to execute one machine cycle by an Intel 80186 microprocessor 2.2 µs: Lifetime of a muon 4–16 µs: Time to execute one machine cycle by a 1960s minicomputer |
| 10−3 | 1 millisecond | ms | One thousandth of one second | 1 ms: time for a neuron in human brain to fire one impulse and return to rest 4–8 ms: typical seek time for a computer hard disk |

In [4]:
small_array = np.random.randint(low=1, high=10, size=5)

%timeit reciprocal(small_array)

9.2 µs ± 680 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [5]:
big_array = np.random.randint(low=1, high=10, size=100_000)

%timeit reciprocal(big_array)

150 ms ± 215 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [25]:
print(f"Size difference   : {100_000/5}")
print(f"Runtime difference: {150e-3/9.2e-6}")

Size difference   : 20000.0
Runtime difference: 16304.347826086956


## Introducing UFuncs

In [7]:
print(reciprocal(small_array))
print(1.0 / small_array)

[0.25       0.16666667 0.33333333 0.2        0.125     ]
[0.25       0.16666667 0.33333333 0.2        0.125     ]


In [8]:
%timeit (1.0 / big_array)

89.1 µs ± 78.9 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [9]:
%timeit np.reciprocal(big_array)

86.3 µs ± 220 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [30]:
print(f"Time for pure python recirpcal   : {150} ms")
print(f"Time for numpy recirpcal (C-code):  {86} us")
print(f"Speedup: {150e-3/86.3e-6:.2f}")

Time for pure python recirpcal   : 150 ms
Time for numpy recirpcal (C-code):  86 us
Speedup: 1738.12


In [11]:
x = np.arange(4)

print(x)

[0 1 2 3]


In [12]:
print(x + 2)
print(x - 2)
print(x * 2)
print(x / 2)

[2 3 4 5]
[-2 -1  0  1]
[0 2 4 6]
[0.  0.5 1.  1.5]


In [13]:
print(x + 2.0)
print(x - 2.0)
print(x * 2.0)
print(x / 2.0)

[2. 3. 4. 5.]
[-2. -1.  0.  1.]
[0. 2. 4. 6.]
[0.  0.5 1.  1.5]


In [14]:
print(np.add(x, 2))

[2 3 4 5]


| Name | Description |
|-|-|
| add | Add arguments element-wise. |
| subtract | Subtract arguments, element-wise. |
| multiply | Multiply arguments element-wise. |
| matmul | Matrix product of two arrays. |
| divide | Returns a true division of the inputs, element-wise. |
| negative | Numerical negative, element-wise. |
| positive | Numerical positive, element-wise. |
| power | First array elements raised to powers from second array, element-wise. |
| mod | Return element-wise remainder of division. |
| absolute | Calculate the absolute value element-wise. |
| fabs | Compute the absolute values element-wise. |
| sign | Returns an element-wise indication of the sign of a number. |
| exp | Calculate the exponential of all elements in the input array. |
| log | Natural logarithm, element-wise. |
| sqrt | Return the non-negative square-root of an array, element-wise. |
| square | Return the element-wise square of the input. |
| reciprocal | Return the reciprocal of the argument, element-wise. |
| gcd | Returns the greatest common divisor of \|x1\| and \|x2\| |
| lcm | Returns the lowest common multiple of \|x1\| and \|x2\| |

In [15]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

In [16]:
print(np.abs(x))

[2 1 0 1 2]


In [17]:
print(np.fabs(x))

[2. 1. 0. 1. 2.]


In [18]:
x = np.array([-2, -1, 0, 1, 2], dtype=np.float32)

print(np.abs(x))
print(np.fabs(x))

[2. 1. 0. 1. 2.]
[2. 1. 0. 1. 2.]


### Trigonometric functions

| Name | Description |
|-|-|
| sin | Trigonometric sine, element-wise. |
| cos | Cosine element-wise. |
| tan | Compute tangent element-wise. |

In [19]:
theta = np.linspace(0, 2.0 * np.pi, 7)

print(theta)

[0.         1.04719755 2.0943951  3.14159265 4.1887902  5.23598776
 6.28318531]


In [20]:
print(np.sin(theta))
print(np.cos(theta))

[ 0.00000000e+00  8.66025404e-01  8.66025404e-01  1.22464680e-16
 -8.66025404e-01 -8.66025404e-01 -2.44929360e-16]
[ 1.   0.5 -0.5 -1.  -0.5  0.5  1. ]


### Bit-twiddling functions

| Name | Description |
|-|-|
| bitwise_and | Compute the bit-wise AND of two arrays element-wise. |
| bitwise_or | Compute the bit-wise OR of two arrays element-wise. |
| bitwise_xor | Compute the bit-wise XOR of two arrays element-wise. |

In [21]:
print(np.bitwise_and(14, 13))
print(np.binary_repr(12))
print(np.bitwise_and([14, 3], 13))

12
1100
[12  1]


### Comparison functions

| Name | Description |
|-|-|
| greater | Return the truth value of (x1 > x2) element-wise. |
| greater_equal | Return the truth value of (x1 >= x2) element-wise. |
| less | Return the truth value of (x1 < x2) element-wise. |
| less_equal | Return the truth value of (x1 <= x2) element-wise. |
| not_equal | Return (x1 != x2) element-wise. |
| equal | Return (x1 == x2) element-wise. |

In [22]:
print(np.greater([4, 2], [2, 2]))

[ True False]


In [23]:
a = np.array([4, 2])
b = np.array([2, 2])

print(a > b)

[ True False]


All standard operators are overloaded to use numpy implementation on numpy objects. Math operators (+, -, *, /, ^, ...) as well as Comparison operators (>, >=, !=, ...)  
So there is no need to call them explicitly by numpy.operator().