# Several Important Numpy Functions

In [121]:
import numpy as np
np.random.seed(0)

In [122]:
def array_info(array: np.ndarray) -> None:
    print(f"ndim: {array.ndim}")
    print(f"shape: {array.shape}")
    print(f"size: {array.size}")
    print(f"dtype: {array.dtype}")
    print(f"values:\n{array}\n")

In [123]:
def compare_arrays(a1: np.ndarray, a2: np.ndarray) -> None:
    print(a1)
    print(a2)

In [124]:
x = np.arange(4).reshape((2, 2))

array_info(x)

ndim: 2
shape: (2, 2)
size: 4
dtype: int32
values:
[[0 1]
 [2 3]]



## Axis Related Functions

np.moveaxis(a, sources, destinations):

This function can be used to rearrange specific dimensions of an array.

In [125]:
x_moved = np.moveaxis(x, source=0, destination=1)

compare_arrays(x, x_moved)

[[0 1]
 [2 3]]
[[0 2]
 [1 3]]


np.transpose(a, axes=None):

This function can be used to rearrange all dimensions of an array at once.

In [126]:
x_transposed = np.transpose(x)

compare_arrays(x, x_transposed)

[[0 1]
 [2 3]]
[[0 2]
 [1 3]]


In [127]:
x_transposed = x.T

compare_arrays(x, x_transposed)

[[0 1]
 [2 3]]
[[0 2]
 [1 3]]


In [128]:
x_rolled = np.roll(x, axis=0, shift=-1)

compare_arrays(x, x_rolled)

[[0 1]
 [2 3]]
[[2 3]
 [0 1]]


In [129]:
x_rolled = np.roll(x, axis=1, shift=-1)

compare_arrays(x, x_rolled)

[[0 1]
 [2 3]]
[[1 0]
 [3 2]]


## Indexing

If the 2 demensional matrix has the shape (2,3) then the resulting index shape is (2,2,3)  
The first 2 is determined by the matrix dimension 2d  
The following dimensions are determined by the matrix shape, in this case 2,3  
In other words the index shape is a matrix of row and column index matrices of type (2,3) `[[row idx], [col idx]]`   
This means if you convert the matrix in an array of row and colum index matrices by accessing `idx[0]` and `idx[1]` you can directly use the returned list of arrays to access the matrix `m[row, col]`  
If you want to access a specific matrix element und access the coordinates (starting from zero) in idx[0] and idx[1].  
Coordinates: $\begin{bmatrix} 00 & 01 & 02 \\ 10 & 11 & 12 \end{bmatrix}$  
For example accessing the coordinate 10, you access the index shape `idx[0]` and `idx[1]`  with (1,0): `m[idx[0,1,0], idx[1,1,0]]` or `m[tuple(idx[:,1,0])` or `m[row[1,0], col[1,0]]`

In [130]:
idxs = np.indices((2, 2))  #better in this case: row, col = np.indices((2, 2))
print(idxs.shape)

print(idxs)

row = idxs[0]
col = idxs[1]
print([row, col])

print(x)
print(x[row, col])

print(x[idxs[0, 1, 0], idxs[1, 1, 0]])
print(x[row[1,0], col[1,0]])
print(x[tuple(idxs[:,1,0])])

(2, 2, 2)
[[[0 0]
  [1 1]]

 [[0 1]
  [0 1]]]
[array([[0, 0],
       [1, 1]]), array([[0, 1],
       [0, 1]])]
[[0 1]
 [2 3]]
[[0 1]
 [2 3]]
2
2
2


In [131]:
idxs = np.diag_indices(2)

print(idxs)

(array([0, 1]), array([0, 1]))


In [132]:
idxs = np.tril_indices(2)

print(idxs)

(array([0, 1, 1]), array([0, 0, 1]))


In [133]:
idxs = np.triu_indices(2)

print(idxs)

(array([0, 0, 1]), array([0, 1, 1]))


In [134]:
c = (x >= 2)
w = np.where(c)

print(c)
print(x)
print(w)
print(x[w])

[[False False]
 [ True  True]]
[[0 1]
 [2 3]]
(array([1, 1], dtype=int64), array([0, 1], dtype=int64))
[2 3]


## Sorting

`np.sort()` returns a sorted copy of the original array  
`np.argx()` functions return a indices list that would sort the original array

In [135]:
y = np.random.randint(low=-10, high=10, size=10)

array_info(y)

ndim: 1
shape: (10,)
size: 10
dtype: int32
values:
[  2   5 -10  -7  -7  -3  -1   9   8  -6]



In [136]:
y_sorted = np.sort(y)

compare_arrays(y, y_sorted)

[  2   5 -10  -7  -7  -3  -1   9   8  -6]
[-10  -7  -7  -6  -3  -1   2   5   8   9]


In [137]:
y_sorted = np.argsort(y)

compare_arrays(y, y_sorted)

[  2   5 -10  -7  -7  -3  -1   9   8  -6]
[2 3 4 9 5 6 0 1 8 7]


In [138]:
y_argmax = np.argmax(y)

print(y_argmax)

7


In [139]:
y_argmin = np.argmin(y)

print(y_argmin)

2
