# Exercise

In [1]:
import numpy as np

## Exercise 1:

Create a 2d array (5x5) with 1 on the border and 0 inside

In [11]:
v1 = np.zeros(shape=(5,5), dtype=np.uint8)
v1[0,:] = 1
v1[-1,:] = 1
v1[:,0] = 1
v1[:,-1] = 1
print(v1)

v2 = np.ones(shape=(5,5), dtype=np.uint8)
v2[1:-1, 1:-1] = 0
print(v2)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


## Exercise 2:

Create a matrix (8x8) and fill it with a checkerboard pattern

In [42]:
M = np.ones(shape=(8,8), dtype=np.uint8)
M[0::2,0::2] = 0
M[1::2,1::2] = 0
print(M)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Exercise 3:

How to find the closest value in an 1D array

In [100]:
N = np.arange(11,dtype=np.uint8)
print(N)
search_val1 = 3.4
search_val2 = 3.5
search_val3 = 3.6
#buggy at tolerance level, maybe use 0.5-floatresolution? or use higher value if size > 1
print(N[np.isclose(N, search_val1, atol=0.5)])
print(N[np.isclose(N, search_val2, atol=0.5)])
print([np.isclose(N, search_val3, atol=0.5)])
print(N[np.isclose(N, search_val2, atol=0.5)][-1])

#only works if N has no gaps
print(N[np.where(N==np.round(search_val1))])
print(N[np.where(N==np.round(search_val2))])
print(N[np.where(N==np.round(search_val3))])

#official solution also is buggy at 0.5
print(N[np.argmin(np.abs(N.astype(np.float64)-search_val1))])
print(N[np.argmin(np.abs(N.astype(np.float64)-search_val2))])
print(N[np.argmin(np.abs(N.astype(np.float64)-search_val3))])

[ 0  1  2  3  4  5  6  7  8  9 10]
[3]
[3 4]
[array([False, False, False, False,  True, False, False, False, False,
       False, False])]
4
[3]
[4]
[4]
3
3
4


## Exercise 4:

How to get the n largest values of an 1D array

In [95]:
O = np.random.uniform(low=0, high=101, size=(10,))
print(O)
n = 3
idx = np.argsort(O)
print(idx)
print(O[idx[-n:]])

[47.43983683 45.32780535  2.58356698 72.42863137 60.16019326 70.44269451
 78.07176619 16.31881255 62.54562173 25.01809275]
[2 7 9 1 0 4 8 5 3 6]
[70.44269451 72.42863137 78.07176619]
