# Exercise

In [30]:
import numpy as np
np.random.seed(0)

In [31]:
def array_info(array: np.ndarray) -> None:
    print(f"ndim: {array.ndim}")
    print(f"shape: {array.shape}")
    print(f"size: {array.size}")
    print(f"dtype: {array.dtype}")
    print(f"values:\n{array}\n")

# Exercise 1

- Create an array (M) with the size 5x5 by sampling from an uniform int distribution $M_{i,j} \in [-10, 10]$

In [32]:
#M = np.random.random_integers(low=-10, high=10, size=(5,5)) #DeprecationWarning: This function is deprecated. Please call randint(-10, 10 + 1) instead
M = np.random.randint(low=-10, high=10+1, size=(5,5))
array_info(M)

ndim: 2
shape: (5, 5)
size: 25
dtype: int32
values:
[[  2   5 -10  -7  -7]
 [ -3  -1   9   8  -6]
 [ -4   2  -9  -4  -3]
 [  4   7  -5   3  -2]
 [ -1  10   9   6   9]]



# Exercise 2

- Create an array (N) with the size 5x5 by sampling from an uniform float distribution $M_{i,j} \in [-10, 10)$

In [33]:
N = np.random.uniform(low=-10, high=10, size=(5,5))
array_info(N)

ndim: 2
shape: (5, 5)
size: 25
dtype: float64
values:
[[ 9.14310318 -7.19298439  7.40174517 -0.52783909  6.01821504]
 [ 0.40954959  3.5775906   4.41265309  1.64039584  0.74746459]
 [ 5.17231249 -7.88184786 -0.52799161 -6.27335313  4.73836354]
 [-5.66899291 -7.29563653 -3.51717984 -7.00650266 -5.55357223]
 [-2.27022038  8.05196951 -1.0010002   2.26126916  8.04697166]]



# Exercise 3

- Count the number of elements of the matrix M and N where the elements are less than 0

In [34]:
M_count = np.count_nonzero(M < 0)
N_count = np.count_nonzero(N < 0)
print(f"Number of values less then zero in M: {M_count}")
print(f"Number of values less then zero in N: {N_count}")

Number of values less then zero in M: 13
Number of values less then zero in N: 12


# Exercise 4

- Replace all values of the matrix M and N that are less than 0 by 0

In [35]:
M[M < 0] = 0
array_info(M)

N_idx = np.where(N < 0)
N[N_idx] = 0
array_info(N)

ndim: 2
shape: (5, 5)
size: 25
dtype: int32
values:
[[ 2  5  0  0  0]
 [ 0  0  9  8  0]
 [ 0  2  0  0  0]
 [ 4  7  0  3  0]
 [ 0 10  9  6  9]]

ndim: 2
shape: (5, 5)
size: 25
dtype: float64
values:
[[9.14310318 0.         7.40174517 0.         6.01821504]
 [0.40954959 3.5775906  4.41265309 1.64039584 0.74746459]
 [5.17231249 0.         0.         0.         4.73836354]
 [0.         0.         0.         0.         0.        ]
 [0.         8.05196951 0.         2.26126916 8.04697166]]



# Exercise 5

- Stack the matrix M and N on the axis=0 to a new matrix O

In [36]:
O = np.vstack([M,N])
array_info(O)

P = np.concatenate([M,N], axis=0)
array_info(P)

ndim: 2
shape: (10, 5)
size: 50
dtype: float64
values:
[[ 2.          5.          0.          0.          0.        ]
 [ 0.          0.          9.          8.          0.        ]
 [ 0.          2.          0.          0.          0.        ]
 [ 4.          7.          0.          3.          0.        ]
 [ 0.         10.          9.          6.          9.        ]
 [ 9.14310318  0.          7.40174517  0.          6.01821504]
 [ 0.40954959  3.5775906   4.41265309  1.64039584  0.74746459]
 [ 5.17231249  0.          0.          0.          4.73836354]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          8.05196951  0.          2.26126916  8.04697166]]

ndim: 2
shape: (10, 5)
size: 50
dtype: float64
values:
[[ 2.          5.          0.          0.          0.        ]
 [ 0.          0.          9.          8.          0.        ]
 [ 0.          2.          0.          0.          0.        ]
 [ 4.          7.          0.          3.          0.        ]
 [ 0. 

# Exercise 6

- Multiply the matrix O by np.pi
- Compute the cos for each value of the matrix O

In [37]:
O = O * np.pi
O = np.cos(O)
array_info(O)

ndim: 2
shape: (10, 5)
size: 50
dtype: float64
values:
[[ 1.         -1.          1.          1.          1.        ]
 [ 1.          1.         -1.          1.          1.        ]
 [ 1.          1.          1.          1.          1.        ]
 [ 1.         -1.          1.         -1.          1.        ]
 [ 1.          1.         -1.          1.         -1.        ]
 [-0.90063323  1.         -0.30379811  1.          0.99836314]
 [ 0.28034964  0.24135129  0.27097752  0.42690418 -0.70145214]
 [-0.85702122  1.          1.          1.         -0.68079039]
 [ 1.          1.          1.          1.          1.        ]
 [ 1.          0.98670152  1.          0.68163515  0.98913191]]

