# Exercise

In [3]:
import numpy as np
np.random.seed(0)

In [4]:
def array_info(array: np.ndarray) -> None:
    print(f"ndim: {array.ndim}")
    print(f"shape: {array.shape}")
    print(f"size: {array.size}")
    print(f"dtype: {array.dtype}")
    print(f"values:\n{array}\n")

## Exercise 1

- Create an array M of shape (3, 3) with zeros at all entries
- Fill the diagonal values with np.pi
- Fill the upper triangular (except the diag) with 1
- Fill the lower triangular (except the diag) with -1

The resulting matrix should have the following values:

```python
[[ 3.14159265  1.          1.        ]
 [-1.          3.14159265  1.        ]
 [-1.         -1.          3.14159265]]
```

In [24]:
M = np.zeros(shape=(3,3), dtype=np.float16)

diag_idx = np.diag_indices_from(M)
M[diag_idx] = np.pi
array_info(M)

triu_idx = np.triu_indices_from(M, k=1)
M[triu_idx] = 1
array_info(M)

tril_idx = np.tril_indices_from(M, k=-1)
M[tril_idx] = -1
array_info(M)


ndim: 2
shape: (3, 3)
size: 9
dtype: float16
values:
[[3.14 0.   0.  ]
 [0.   3.14 0.  ]
 [0.   0.   3.14]]

ndim: 2
shape: (3, 3)
size: 9
dtype: float16
values:
[[3.14 1.   1.  ]
 [0.   3.14 1.  ]
 [0.   0.   3.14]]

ndim: 2
shape: (3, 3)
size: 9
dtype: float16
values:
[[ 3.14  1.    1.  ]
 [-1.    3.14  1.  ]
 [-1.   -1.    3.14]]



## Exercise 2

- Get the indicies where the matrix values are greater than or equal to one

In [28]:
idx = np.where(M >= 1)
print(idx)
#array_info(M[idx])

(array([0, 0, 0, 1, 1, 2], dtype=int64), array([0, 1, 2, 1, 2, 2], dtype=int64))
